server:
  port: 8088

spring:
  application:
    name: TTMM
  datasource:
    url: jdbc:mysql://192.168.2.111:3306/ttmm?zeroDateTimeBehavior=convertToNull&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
#    schema: classpath:database/import.sql
#    sql-script-encoding: utf-8
#    initialization-mode: ALWAYS
## json配置
  jackson:
    time-zone: Asia/Shanghai
  jpa:
    open-in-view: true
    database: mysql
    showSql: true
    hibernate:
      ddlAuto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
#  redis:
#    # Redis数据库索引（默认为0）
#    database: 0
#    host: 192.168.2.111
#    port: 6379
#    password:
#    jedis:
#      pool:
#        # 连接池最大连接数（使用负值表示没有限制）
#        max-active: 8
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1
#        # 连接池中的最大空闲连接
#        max-idle: 8
#        # 连接池中的最小空闲连接
#        min-idle: 0
#    # 连接超时时间（毫秒）
  data:
    redis:
      repositories:
#        关闭日志打印
        enabled: false
#    connect-timeout: 120

#MyBatis扫描mapper文件配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:log/logback.xml

#  level: debug

#分页插件
pagehelper:
  # dialect: ①
  # 分页插件会自动检测当前的数据库链接，自动选择合适的分页方式（可以不设置）
  helper-dialect: mysql
  # 上面数据库设置后，下面的设置为true不会改变上面的结果（默认为true）
  auto-dialect: true
  page-size-zero: false # ②
  reasonable: true # ③
  # 默认值为 false，该参数对使用 RowBounds 作为分页参数时有效。（一般用不着）
  offset-as-page-num: false
  # 默认值为 false，RowBounds是否进行count查询（一般用不着）
  row-bounds-with-count: false
  #params: ④
  #support-methods-arguments: 和params配合使用，具体可以看下面的讲解
  # 默认值为 false。设置为 true 时，允许在运行时根据多数据源自动识别对应方言的分页
  auto-runtime-dialect: false # ⑤
  # 与auto-runtime-dialect配合使用
  close-conn: true
  # 用于控制默认不带 count 查询的方法中，是否执行 count 查询，这里设置为true后，total会为-1
  default-count: false
  #dialect-alias: ⑥
